name: Release

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IJ_PLUGIN_REPO_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "openjdk@1.17.0"

      - name: Package plugin
        # The first packageArtifact creates the files (including plugin.xml).
        # The second packageArtifactZip allows the patchPluginXML task to run
        #   on those files and patch the plugin.xml.
        # Then it packages files into a single zip archive.
        run: sbt clean && sbt packageArtifact && sbt packageArtifactZip

      - name: Publish plugin
        run: sbt "publishPlugin Stable"
